[workspace]
resolver = "3"
members = ["launcher", "injected_dll"]

[workspace.package]
version = "0.1.0"
edition = "2024"

# https://github.com/CasualX/pelite/issues/287
[patch.crates-io]
pelite = { git = "https://github.com/lifegpc/pelite.git", rev = "d4fad2a01a9a1a71e36f10f312112bd9b63c9a3d"}
